### ISSUE TITLE
New Julia user trying to work with UEM

### ISSUE THREAD

**Issue by jste251** [JuliaEconometrics/UEM.jl#2]
Hi,
I am attempting to use this package to create Fixed Effect model and a Random Effects model but keep getting an error in the `model` part of the code would you be able to advise? 
If it is of any use I am trying to replicate the results in the Woooldridge textbook with the Wagepan data.
Thanks,
J
```
using DataFrames, MixedModels, FixedEffectModels, UEM, StatsBase, Base.Test
data=readtable("wagepan.csv")
data[:blackpool] = pool(data[:black])
data[:hisppool] = pool(data[:hisp])
data[:educpool] = pool(data[:educ])
data[:yearpool] = pool(data[:year])
fm = @formula(lwage ~ yearpool + educ + blackpool + hisppool + exper + expersq + married + union)
model = uem(:PO, fm, data)
```

**Comment by Nosferican** [comment]
Hi, this package is part of a series in development and is not productive ready yet. However, let me see if I can take a look at which version of the code this package uses and get back at you.

The production ready package will be in JuliaEconometrics/Econometrics.jl, but I am waiting for 0.7 and the ecosystem to update before releasing it.

---- Edit
After verifying compatibility, the package only works with DataFrames v0.11.3 and up.

**Comment by Nosferican** [comment]
Taking a look at Jeff's dataset, the Stata command would be something like
```
// ssc install bcuse
bcuse wagepan, clear
xtset nr year
xtreg lwage i.year c.exper##c.exper i.married i.union, fe
xtreg lwage i.year i.educ i.black i.hisp c.exper##c.exper i.married i.union
```
note that certain features I dropped from the model due to collinearity (e.g., can't estimate time invariant covariates with individual fixed effects such as race and ethnicity). The model you described is a two-way fixed effects model as you are including both individual and temporal fixed effects. If you indeed think year effects are proper, the model can be run in Stata as
```
/// ssc install reghdfe
reghdfe lwage expersq i.married i.union, a(nr year)
```
in the latest version of the Julia code (I am assuming you are using JuliaPro from `pool` rather than `categorical!` which means you are using the previous JuliaData ecosystem) it would be
```
data = CSV.read("wagepan.csv");
categorical!(data, [:nr, :year, :married, :black, :hisp, :educ])
fm = @formula lwage ~ exper + expersq + married + union + (absorb = nr + year)
model = EconometricsModel(fm, data)
coeftable(model)
```
I will see if I can get you some code to run it in a bit and welcome to Julia 😃.

**Comment by Nosferican** [comment]
This is where development is currently happening [Econometrics.jl](https://github.com/Nosferican/Econometrics.jl).
